#define INCLUDE_TKN 1
#define DEFINE_TKN 2
#define IFNDEF_TKN 3
#define ENDIF_TKN 4

#define CHAR_TKN 11
#define BOOL_TKN 12
#define SHORT_TKN 13
#define INT_TKN 14
#define LONG_TKN 15
#define FLOAT_TKN 16
#define DOUBLE_TKN 17
#define VOID_TKN 18
#define AUTO_TKN 19

#define SIGNED_TKN 31
#define UNSIGNED_TKN 32
#define CONST_TKN 32
#define STATIC_TKN 33

#define IF_TKN 41
#define ELSE_TKN 42

#define FOR_TKN 43
#define WHILE_TKN 44
#define BREAK_TKN 45
#define CONTINUE_TKN 46
#define GOTO_TKN 47
#define DO_TKN 48

#define SWITCH_TKN 51
#define CASE_TKN 52
#define DEFAULT_TKN 53

#define STRUCT_TKN 61
#define UNION_TKN 62
#define TYPEDEF_TKN 63
#define ENUM_TKN 64
#define REGISTER_TKN 65

#define EXTERN_TKN 71
#define RETURN_TKN 72

#define SIZEOF_TKN 81
#define VOLATILE_TKN 82

#define LEFT_BRACES_TKN 101
#define LEFT_BRACKETS_TKN 103
#define LEFT_PARENTHESIS_TKN 105

#define RIGHT_BRACES_TKN 102
#define RIGHT_BRACKETS_TKN 104
#define RIGHT_PARENTHESIS_TKN 106

#define OPERATOR_INC_TKN 111
#define OPERATOR_DEC_TKN 112

#define OPERATOR_PLUS_TKN 113
#define OPERATOR_MINUS_TKN 114
#define OPERATOR_MULT_TKN 115
#define OPERATOR_DIV_TKN 116
#define OPERATOR_MOD_TKN 117

#define OPERATOR_PLUS_EQUAL_TKN 118
#define OPERATOR_MINUS_EQUAL_TKN 119
#define OPERATOR_MULT_EQUAL_TKN 120
#define OPERATOR_DIV_EQUAL_TKN 121
#define OPERATOR_MOD_EQUAL_TKN 122

#define OPERATOR_BITOR_TKN 123
#define OPERATOR_BITAND_TKN 124
#define OPERATOR_XOR_TKN 125
#define OPERATOR_NOT_TKN 126

#define OPERATOR_BITOR_EQUAL_TKN 127
#define OPERATOR_BITAND_EQUAL_TKN 128
#define OPERATOR_XOR_EQUAL_TKN 129
#define OPERATOR_NOT_EQUAL_TKN 130

#define OPERATOR_OR_TKN 131
#define OPERATOR_AND_TKN 132

#define OPERATOR_ASSIGN_TKN 133
#define OPERATOR_EQUAL_TKN 134

#define VARIABLE_TKN 150
#define REALNO_TKN 151
#define STRINGLITERAL_TKN 152
#define CHARLITERAL_TKN 153
